export const getYouTubeId = (url: string): string | null => {
  if (!url) return null;
  // This regex handles various YouTube URL formats:
  // - youtube.com/watch?v=...
  // - youtu.be/...
  // - youtube.com/embed/...
  // - youtube.com/v/...
  // - youtube.com/live/...
  // - m.youtube.com/...
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=|live\/)([^#&?]*).*/;
  const match = url.match(regExp);

  return (match && match[2].length === 11) ? match[2] : null;
};